export const LANG_EXTENSION_MAP = {
    clike: "c",
    css: "css",
    dart: "dart",
    django: "html",
    dockerfile: "dockerfile",
    go: "go",
    htmlmixed: "html",
    javascript: "js",
    jsx: "jsx",
    markdown: "md",
    php: "php",
    python: "py",
    r: "r",
    rust: "rs",
    ruby: "rb",
    sass: "scss",
    shell: "sh",
    sql: "sql",
    swift: "swift",
    xml: "xml",
    yaml: "yaml",
};
